name: Extramentals
version: ${project.version}
main: me.dragontos.extramentals.Extramentals
api-version: 1.19
depends: [PlaceholderAPI]
commands:
  Extramentals:
    subcommands:
      hello:
      bye:
  Discord:
  Dc:
  Gui:
  gm:
  gmc:
  gms:
  gma:
  gmsp:
  fly:
  heal:
  feed:
  god:
  day:
  night:
  sun:
  rain:
  thunder:
  ec:
  enderchest:
  points:
  EXA:


